### ISSUE TITLE
[Feature suggestion] Add Support for Eco Plugins

### ISSUE THREAD

**Issue by Mc35367** [OhTheDungeon/OhTheDungeon#71]
It would be really nice if the plugin had support for the eco plugins, because this would help to make custom items and custom bosses much easier for some people. 
Here is a link to their wiki: https://plugins.auxilor.io/

**Comment by OhTheDungeon** [comment]
It doesnt provide any API and as a premium plugin, it doesnt give dev access to it, so its impossible

**Comment by Mc35367** [comment]
The Eco plugins are all open-source and have a API 
https://plugins.auxilor.io/ecoenchants/api
https://plugins.auxilor.io/ecobosses/api
https://plugins.auxilor.io/talismans/api
https://plugins.auxilor.io/ecoarmor/api
https://plugins.auxilor.io/ecoitems/api

**Comment by OhTheDungeon** [comment]
Ok, I dont know how you are going to use those plugin with this one, please describe in detail, or give out some examples

**Comment by Mc35367** [comment]
So Ecobosses would be a replacement for mythicmobs to create the Boss of the dungeon and the other eco items would be used for the loottables.

**Comment by OhTheDungeon** [comment]
we already provide the system of letting user make  their custom loots so I didnt see why we need to make a special hook here

**Comment by Mc35367** [comment]
Because the possibilities to make unique items with their effect system is much better and you have more stuff to customize.

**Comment by OhTheDungeon** [comment]
sorry I'm not going to do those special custom hook to other plugins, as OTD is designed for vanilla style Minecraft.
If somebody needs that, they can develop their own addon to override the loot generation in OTD, with their customize, instead of merging this into the main OTD.
As the current loot system is already providing support to item with Eco, there's nothing more we could do here.

**Comment by Mc35367** [comment]
And what about ecobosses ?
